version: '3.8'

services:
  app:
    image: lacework/test-latest-dockerhub-tag
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - prod-db-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  prod-db-data: