version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: default

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: catsupplies_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
